config/routes.rb
Rails.application.routes.draw do
  get '/search-products' => 'products#search'
  post '/category' => 'products#category'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'products/new-review/:product_id' => 'reviews#new'
  resources :reviews
  resources :product_images
  # devise_for :users
  devise_for :users, controllers: { confirmations: 'confirmations' }
  root 'products#new'
  get '/products/delete/:id' => 'products#destroy'
  resources :products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/product.rb
class Product < ApplicationRecord
    validates :title, presence:true, length: {minimum:3, maximum:50}
    validates :price, presence:true, :numericality =>{:greater_than_or_equal_to => 1}
    validates :description, presence:true, length: {minimum:10, maximum:200}
    serialize :image, Array
    mount_uploaders :image, ImageUploader    
    has_many :reviews
end

app/models/product_image.rb
class ProductImage < ApplicationRecord
    mount_uploader :image, ImageUploader
    belongs_to :product
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :product
    belongs_to :user
    validates :user_id, presence: true
    validates :product_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :reviews
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable , :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/confirmations_controller.rb
class ConfirmationsController < Devise::ConfirmationsController
    private
    def after_confirmation_path_for(resource_name, resource)
      new_user_session_path
    end
  end

app/controllers/product_images_controller.rb
class ProductImagesController < ApplicationController
  before_action :set_product_image, only: %i[ show edit update destroy ]

  # GET /product_images or /product_images.json
  def index
    @product_images = ProductImage.all
  end

  # GET /product_images/1 or /product_images/1.json
  def show
  end

  # GET /product_images/new
  def new
    @product_image = ProductImage.new
  end

  # GET /product_images/1/edit
  def edit
  end

  # POST /product_images or /product_images.json
  def create
    @product_image = ProductImage.new(product_image_params)

    respond_to do |format|
      if @product_image.save
        format.html { redirect_to @product_image, notice: "Product image was successfully created." }
        format.json { render :show, status: :created, location: @product_image }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /product_images/1 or /product_images/1.json
  def update
    respond_to do |format|
      if @product_image.update(product_image_params)
        format.html { redirect_to @product_image.post, notice: 'Post attachment was successfully updated.' }
      end 
    end
  end

  # DELETE /product_images/1 or /product_images/1.json
  def destroy
    @product_image.destroy
    respond_to do |format|
      format.html { redirect_to products_path, notice: "Product image was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product_image
      @product_image = ProductImage.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def product_image_params
      params.require(:product_image).permit(:product_id, :image)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: %i[ show edit update destroy ]

  def search
    @products = Product.all
  end

  def category
     @category = params[:category]   
     @products = Product.where('category' => @category)
  end

  def index
    @products = Product.paginate(page: params[:page], per_page: 5)
  end

  def show    
  end

  def new
    @product = Product.new
  end

  def edit
  end

  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        params[:product_images]['image'].each do |a|
          @product_image = @product.product_images.create!(:image => a)
       end
        format.html { redirect_to @product, notice: "Product was successfully created." }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: "Product was successfully updated." }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: "Product was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:title, :description, :price, :category ,product_images_attributes: [:id, :product_id, :image])
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: %i[ edit update destroy ]

  # GET /reviews or /reviews.json
  def index
    @reviews = Review.all
  end

  # GET /reviews/1 or /reviews/1.json
  def show
    # @review = Review.all
    @product = Product.find(params[:id])
    @review = @product.reviews
  end

  # GET /reviews/new
  def new
    product_id = params[:product_id]
    @review = Review.new
    @review.product_id = product_id
  end

  # GET /reviews/1/edit
  def edit
  end
  
  # POST /reviews or /reviews.json
  def create
    @review = Review.new(review_params)
    @review.user = current_user
    respond_to do |format|
      if @review.save
        format.html { redirect_to '/products', notice: "Review was successfully created." }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reviews/1 or /reviews/1.json
  def update
    respond_to do |format|
      if @review.update(review_params)
        format.html { redirect_to '/products', notice: "Review was successfully updated." }
        format.json { render :show, status: :ok, location: @review }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1 or /reviews/1.json
  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to reviews_url, notice: "Review was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_review
      @review = Review.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def review_params
      params.require(:review).permit(:comment, :rating, :product_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/product_images_helper.rb
module ProductImagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-expand-md navbar-collapse navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to 'Shopping App', root_path, class: "navbar-brand" %>
    <button
      class="navbar-toggler"
      type="button"
      data-toggle="collapse"
      data-target="#navbarSupportedContent"
      data-bs-toggle="collapse"
      data-bs-target="#navbarSupportedContent"
      aria-controls="navbarSupportedContent"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to 'Search Products', "/search-products", class: "nav-link" %>
        </li>
        <li class="nav-item"><%= link_to 'View Products', products_path, class: "nav-link" %></li>
        <li class="nav-item">
          <%= link_to 'Edit User', edit_user_registration_path, class: "nav-link" %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= button_to 'Logout', destroy_user_session_path, method: :delete, :class=> "btn
          btn-danger"%>
        </li>
      </ul>
      <ul>
        <% else %>
      </ul>
      <ul class="navbar-nav">
        <li class="nav-item">
          <%= link_to 'Sign Up', new_user_registration_path, class: "btn btn-primary" %>
        </li>
        &nbsp;&nbsp;
        <li class="nav-item">
          <%= link_to 'Sign In', new_user_session_path, class: "btn btn-success" %>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css" integrity="sha384-GJzZqFGwb1QTTN6wy59ffF1BuGJpLSa9DkKMp0DgiMDm4iYMj70gZWKYbI706tWS" crossorigin="anonymous">

    <title>ShoppingApp</title>
    
  </head>

  <body>
    <%= render 'layouts/navigation' %> 
    
    <% flash.each do |type, msg| %>
      
      <% if type=='alert' %>
        <% type='alert alert-danger' %>
        <% elsif type=='notice' then type="alert alert-success" end %>
      <div class="<%= type %>" role="alert"><%= msg %></h4></div>
    
    <% end %>
    <div class="container"> <%= yield %> </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.6/umd/popper.min.js" integrity="sha384-wHAiFfRlMFy6i5SRaxvfOCifBUQy1xHdJ/yoi7FRNXMRBu5WHdZYu1hA6ZOblgut" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/js/bootstrap.min.js" integrity="sha384-B0UglyR+jN6CkvvICOB2joaf5I4l3gm9GU6Hc1og6Ls7i6U/mkkaduKaBhlAXv9k" crossorigin="anonymous"></script>
  </body>
</html>

app/views/product_images/_form.html.erb
<%= form_with(model: product_image) do |form| %> <% if product_image.errors.any? %>
<div id="error_explanation">
  <h2>
    <%= pluralize(product_image.errors.count, "error") %> prohibited this product_image from being
    saved:
  </h2>

  <ul>
    <% product_image.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %> <%= image_tag @product_image.image %> <%= form_for(@product_image) do |f| %>
<div class="field">
  <%= f.label :image %><br />
  <%= f.file_field :image %>
</div>
<div class="actions"><%= f.submit %></div>
<% end %>

<div class="field"><%= form.label :product_id %> <%= form.number_field :product_id %></div>

<div class="field"><%= form.label :image %> <%= form.text_field :image %></div>

<div class="actions"><%= form.submit %></div>
<% end %>

app/views/product_images/edit.html.erb
<h1>Editing Product Image</h1>

<%= render 'form', product_image: @product_image %>

<%= link_to 'Show', @product_image %> |
<%= link_to 'Back', product_images_path %>

app/views/product_images/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Product Images</h1>

<table>
  <thead>
    <tr>
      <th>Product</th>
      <th>Image</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @product_images.each do |product_image| %>
      <tr>
        <td><%= product_image.product_id %></td>
        <td><%= product_image.image %></td>
        <td><%= link_to 'Show', product_image %></td>
        <td><%= link_to 'Edit', edit_product_image_path(product_image) %></td>
        <td><%= link_to 'Destroy', product_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/product_images/new.html.erb
<h1>New Product Image</h1>

<%= render 'form', product_image: @product_image %>

<%= link_to 'Back', product_images_path %>

app/views/product_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Product:</strong>
  <%= @product_image.product_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product_image.image %>
</p>

<%= link_to 'Edit', edit_product_image_path(@product_image) %> |
<%= link_to 'Back', product_images_path %>

app/views/products/_form.html.erb
<%= form_with(model: product) do |form| %> <% if product.errors.any? %>
<div id="error_explanation">
  <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

  <ul>
    <% product.errors.each do |error| %>
    <li><%= error.full_message %></li>
    <% end %>
  </ul>
</div>
<% end %>
<div style="width: 50%; border: 1px solid; padding: 30px; border-radius: 1%">
  <div class="form-group">
    <%= form.label :title , :class => "exampleInputPassword1" %> <%= form.text_field :title ,
    :required => true , :maxlength => 20, :minlength => 5 , :class => "form-control" %>
  </div>
  <br />

  <div class="form-group">
    <%= form.label :description %> <%= form.text_area :description , :required => true,
    :maxlength=>200, :minlength => 10 , :class => "form-control" %>
  </div>
  <br />

  <div class="form-group">
    <%= form.label :price %> <%= form.number_field :price , :required => true, :min => 1 , :class=>
    "form-control" %>
  </div>
  <br />

  <%= form.fields_for :product_images do |p| %>
  <div class="form-group">
    <%= p.label :image %><br />
    <%= p.file_field :image, :multiple => true, name: "product_images[image][]" , :required => true
    %>
  </div>
  <br />
  <% end %>

  <div class=""><%= form.submit "Create Product", :class => 'btn btn-success' %></div>
  <br />
</div>
<% end %>

app/views/products/category.html.erb
<p id="notice"><%= notice %></p>
<h1>Products refined by: <%= @category%></h1>
<%= form_tag('/category') do |form| %>

<div class="form-group">
  Category <%= select_tag "category", options_for_select([ 'Select One', 'Food', 'Laptop',
  'Refrigerator', 'Television', 'Computer', 'PC Accessories', 'Clothes', 'Camera', 'Toys', 'Other'
  ], "MasterCard") %>
</div>

<div class=""><%= submit_tag "Find By Category" %></div>
<br />
<% end %>

<div class="table-responsive-md">
  <table class="table table-striped table-hover table-dark table-bordered">
    <colgroup>
      <col span="1" style="width: 3%" />
      <col span="1" style="width: 10%" />
      <col span="1" style="width: 60%" />
      <col span="1" style="width: 20%" />
      <col span="1" style="width: 8%" />
    </colgroup>
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Category</th>
        <th scope="col">Price</th>
        <th scope="col">View</th>
      </tr>
    </thead>

    <tbody>
      <% number =0 %> <% @products.each do |product| %>
      <tr>
        <td scope="row"><%= number+=1%></td>
        <td scope="row"><%= product.title %></td>
        <td scope="row"><%= product.description %></td>
        <td scope="row"><%= product.category %></td>
        <td scope="row"><%= product.price %></td>

        <td scope="row"><%= link_to 'Show', product, class: "btn btn-success" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br />

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>
<%= will_paginate @products %>
<h1>Products</h1>
<%= form_tag('/category') do |form| %>

<div class="form-group">
  Category <%= select_tag "category", options_for_select([ 'Food', 'Laptop', 'Refrigerator',
  'Television', 'Computer', 'PC Accessories', 'Clothes', 'Camera', 'Toys', 'Other' ], "MasterCard")
  %>
</div>

<div class=""><%= submit_tag "Find By Category" %></div>
<br />
<% end %>

<div class="table-responsive-md">
  <table class="table table-striped table-hover table-dark table-bordered">
    <colgroup>
      <col span="1" style="width: 3%" />
      <col span="1" style="width: 10%" />
      <col span="1" style="width: 60%" />
      <col span="1" style="width: 20%" />
      <col span="1" style="width: 8%" />
    </colgroup>
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Images</th>
        <th scope="col">Description</th>
        <th scope="col">Category</th>
        <th scope="col">Price</th>
        <th scope="col">View</th>
      </tr>
    </thead>

    <tbody>
      <% number =0 %> <% @products.each do |product| %>
      <tr>
        <td scope="row"><%= number+=1%></td>
        <td scope="row"><%= product.title %></td>
        <td>
          <div class="row">
            <% product.image.each do |img| %>
            <div class="col">
              <center>
                <% if img.url %> <%= image_tag img.url, :style => "width:100px;height:80px" %>
                <br />
                <%end%>
              </center>
            </div>

            <% end %>
          </div>
        </td>
        <td scope="row"><%= product.description %></td>
        <td scope="row"><%= product.category %></td>
        <td scope="row"><%= product.price %></td>

        <td scope="row"><%= link_to 'Show', product, class: "btn btn-success" %></td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
<br />

app/views/products/new.html.erb
<% if user_signed_in? %> <br /><br />
<div style="margin-left: 10%; min-width: 600px; margin-right: 10%">
  <h1>Welcome!!</h1>
  <br />
   <%= link_to 'View Products', products_path %> <% else %>
</div>
<h2>
  Please Sign In to continue <%= link_to 'SignIn', new_user_session_path, class: "nav-link" %>
</h2>
<% end%>

app/views/products/search.html.erb
<br />
<br />

<form class="form-inline my-2 my-lg-0">
  <input
    class="form-control mr-sm-2"
    type="search"
    id="search-bar"
    placeholder="Search for a Product"
    aria-label="Search"
  />
</form>
<br /><br />
<div class="table-responsive-md">
  <table class="table table-striped table-hover table-dark table-bordered">
    <colgroup>
      <col span="1" style="width: 3%" />
      <col span="1" style="width: 10%" />
      <col span="1" style="width: 60%" />
      <col span="1" style="width: 20%" />
      <col span="1" style="width: 8%" />
    </colgroup>
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Description</th>
        <th scope="col">Category</th>
        <th scope="col">Price</th>
        <th scope="col">View</th>
      </tr>
    </thead>

    <tbody id="search-products"></tbody>
  </table>
</div>

<script>

  const show = (results) => {
    let number=0
    document.getElementById("search-products").innerHTML = ""
    results.map(product => {
      document.getElementById("search-products").innerHTML +=  `<tr>
        <td scope="row"> ${number+=1} </td>
        <td scope="row"> ${product.title}  </td>
        <td scope="row"> ${product.description}  </td>
        <td scope="row"> ${product.category}  </td>
        <td scope="row"> ${product.price}  </td>

        <td scope="row"> <a href="/products/${product.id}"> Display </a>  </td>
      </tr>
      `
    })
  }
  var products=[]
  let result= []
   <% @products.each do |product| %>

   products.push({title:'<%= product.title%>', description:'<%= product.description%>', id:'<%= product.id%>', category: '<%= product.category%>', price: '<%= product.price%>'})
    <% end %>
    console.log(products)
    document.getElementById("search-bar").addEventListener('keyup',(e)=> {
      result= []
      for(let obj of products){
        if (obj.title.toLowerCase().includes(e.target.value.toLowerCase()) || (obj.description.toLowerCase().includes(e.target.value.toLowerCase())))
        result.push(obj)
      }
      console.log(result)
      show(result)
    })
</script>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>
<h1><%= @product.title%> </h1>


<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Category:</strong>
  <%= @product.category %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Images:</strong>
  <div class="display: grid; grid-template-columns: auto auto auto;">
  <% @product.image.each do |img| %>
  <% if img.present? %>
    <p><%= image_tag img.url , :style => "width: 20%; height: 20%;" %></p>
  <% end %>
  <% end %>
</div>
</p>

<h2>Reviews of <%= @product.title %></h2>
<div class="table-responsive-md">
  <table class="table table-striped table-hover table-dark table-bordered">
    <colgroup>
      <col span="1" style="width: 3%" />
      <col span="1" style="width: 70%" />
      <col span="1" style="width: 5%" />
      <col span="1" style="width: 11%" />
      <col span="1" style="width: 11%" />
    </colgroup>
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Comment</th>
        <th scope="col">Rating</th>
        <th scope="col">Product Id</th>
        <th scope="col">User Email</th>
        <th scope="col">Edit</th>
      </tr>
    </thead>

    <tbody>
      <% number =0 %> <% @product.reviews.each do |review| %>
      <tr>
          <% user = User.find(review.user_id) %>
        <td scope="row"><%= number+=1%></td>
        <td scope="row"><%= review.comment %></td>
        <td scope="row"><%= review.rating %></td>
        <td scope="row"><%= review.product_id %></td>
        <td scope="row"><%= user.email%></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
  <br />

  <%= link_to 'New Review', 'new-review/'+@product.id.to_s %>
</div>

app/views/reviews/edit.html.erb
<h1>Editing Review</h1>

<%= render 'form', review: @review %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews</h1>

<div class="table-responsive-md">
  <table class="table table-striped table-hover table-dark table-bordered">
    <colgroup>
      <col span="1" style="width: 3%" />
      <col span="1" style="width: 70%" />
      <col span="1" style="width: 5%" />
      <col span="1" style="width: 11%" />
      <col span="1" style="width: 11%" />
    </colgroup>
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Comment</th>
        <th scope="col">Rating</th>
        <th scope="col">Product_Id</th>
        <th scope="col">View</th>
        <th scope="col">Edit</th>
        <th scope="col">Delete</th>
      </tr>
    </thead>

    <tbody>
      <% number =0 %> <% @reviews.each do |review| %>
      <tr>
        <td scope="row"><%= number+=1%></td>
        <td scope="row"><%= review.comment %></td>
        <td scope="row"><%= review.rating %></td>
        <td scope="row"><%= review.product_id %></td>
        <td><%= link_to 'Show', review %></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        <td>
          <%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
  <br />

  <%= link_to 'New Review', new_review_path %>
</div>

app/views/reviews/new.html.erb
<h1>New Review for product<%= @review.product_id%></h1>

<%= render 'form', review: @review %> <%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<h1>Reviews for Product <%= @product_name%> </h1>

<div class="table-responsive-md">
  <table class="table table-striped table-hover table-dark table-bordered">
    <colgroup>
      <col span="1" style="width: 3%" />
      <col span="1" style="width: 70%" />
      <col span="1" style="width: 5%" />
      <col span="1" style="width: 11%" />
      <col span="1" style="width: 11%" />
    </colgroup>
    <thead class="thead-dark">
      <tr>
        <th scope="col">#</th>
        <th scope="col">Comment</th>
        <th scope="col">Rating</th>
        <th scope="col">Product Id</th>
        <th scope="col">User Email</th>
        <th scope="col">Edit</th>
      </tr>
    </thead>

    <tbody>
      <% number =0 %> <% @review.each do |review| %>
      <tr>
          <% user = User.find(review.user_id) %>
        <td scope="row"><%= number+=1%></td>
        <td scope="row"><%= review.comment %></td>
        <td scope="row"><%= review.rating %></td>
        <td scope="row"><%= review.product_id %></td>
        <td scope="row"><%= user.email%></td>
        <td><%= link_to 'Edit', edit_review_path(review) %></td>
        
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
  <br />

  <%= link_to 'New Review', 'new-review/'+@product_id.to_s %>
</div>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>